### ISSUE TITLE
Add dotnet-template tag 

### ISSUE THREAD

**Issue by sayedihashimi** [NetCoreApps/templates#1]
I have created a "dotnet-template" tag in github, can you add the tag to this repository so it shows up in the [dotnet-template](https://github.com/search?q=topic%3Adotnet-template&type=Repositories) search result?

**Comment by mythz** [comment]
Sure, looks like it's showing up now: https://github.com/search?q=topic%3Adotnet-template&type=Repositories

Cheers 👍

**Comment by sayedihashimi** [comment]
Thanks
