### ISSUE TITLE
Error in create new project command.

### ISSUE THREAD

**Issue by ristaloff** [NetCoreApps/templates#2]
I think the command to create a new ss-empty project should be:
`dotnet new ss-empty -o MyApp -n MyApp`
not 
`dotnet new -i ss-empty -o MyApp -n MyApp`

The "-i" seems to be causing trouble.

**Comment by Layoric** [comment]
@ristaloff You're right, that was just a bad copy/paste.

Also, these were tested when `dotnet new` was still not finished. I've found the `dotnet new` experience not that good so not sure if these templates in this project will be around for .NET 2.0, but hope they are useful for now for those still on 1.1. Cheers! 👍
