### ISSUE TITLE
The ss-empty project won't build

### ISSUE THREAD

**Issue by ristaloff** [NetCoreApps/templates#3]
To build and run the ss-empty project I had to remove and recreate the test project.
The test project referenced an older version of .netcore. But I could not upgrade it. I got the message "Blocked by project" in the nuget manager.

**Comment by Layoric** [comment]
I had this working with .NET 1.1.1 (CLI 1.03?) and tested with point in time of the `templates` `dotnet new3` tools so not surprised this won't build. Had a lot of issues with VS tooling. 

Suggestion would be to use the `git clone` method of installing and trying out the templates if you're really interested but this repo is still really just trying out the updates to `dotnet new` to see what kind of experience we could build with `dotnet new`.
